version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: eer6eigh9ooDe4po
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    image: rails-base
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      POSTGRES_PASSWORD: eer6eigh9ooDe4po

  worker:
    command: bundle exec que
    build: .
    depends_on:
      - db
    image: rails-base
    restart: always
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      POSTGRES_PASSWORD: eer6eigh9ooDe4po

volumes:
  bundle_cache:
