version: '3.1'

services:
  app1:
    build: .
    image: rails-base
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      REDIS_URL: redis://z1.0x7cbi.ng.0001.euw1.cache.amazonaws.com:6379
      APP_QUEUE: q1

  worker1:
    command: bundle exec sidekiq -q q99
    build: .
    image: rails-base
    restart: always
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      REDIS_URL: redis://z1.0x7cbi.ng.0001.euw1.cache.amazonaws.com:6379
      RAILS_MAX_THREADS: 20

  worker2:
    command: bundle exec sidekiq -q q2
    build: .
    image: rails-base
    restart: always
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      REDIS_URL: redis://z1.0x7cbi.ng.0001.euw1.cache.amazonaws.com:6379
      RAILS_MAX_THREADS: 20

volumes:
  bundle_cache:
