version: '3.1'

services:
  app:
    build: .
    image: rails-base
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      REDIS_URL: redis://z1.0x7cbi.ng.0001.euw1.cache.amazonaws.com:6379

  worker:
    command: bundle exec sidekiq
    build: .
    image: rails-base
    restart: always
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      REDIS_URL: redis://z1.0x7cbi.ng.0001.euw1.cache.amazonaws.com:6379

volumes:
  bundle_cache:
